//plugins {
//  id "de.gesellix.docker" version "2016-09-09T17-53-52"
//}
apply plugin: 'java'

version = '1.2.0-SNAPSHOT'
sourceCompatibility = 1.17
targetCompatibility = 1.17

repositories {
//    jcenter()
    mavenLocal()
    mavenCentral()
}

dependencies {
    compileOnly 'javax.servlet:javax.servlet-api:3.1.0'
    compileOnly 'org.apache.commons:commons-lang3:3.20.0'
    compileOnly ('edu.internet2.middleware.grouper:grouper:6.1.0') {
        transitive = false
    }
    compileOnly ('edu.internet2.middleware.grouper:grouper-ui:6.1.0') {
        transitive = false
    }
    compileOnly ('edu.internet2.middleware.grouper:grouperClient:6.1.0') {
        transitive = false
    }
    compileOnly 'org.slf4j:slf4j-api:1.7.36'
    compileOnly 'org.hibernate:hibernate-core:5.6.15.Final'
    compileOnly 'commons-logging:commons-logging:1.3.5'
}

//docker {
//    dockerHost = System.env['DOCKER_HOST']?.replace("tcp", "http");
//}

task copyDocker(type: Copy) {
    from 'src/test/docker-compose/'
    into 'build/docker-compose/'
}

task copyJspToDocker(type: Copy) {
    dependsOn copyDocker

    from 'src/main/webapp/'
    into 'build/docker-compose/grouper/webapp'
}

task addLib(type: Copy) {
    dependsOn jar

    from 'build/libs/'
    into 'build/docker-compose/grouper/lib/'
}

task buildImage(type: Exec) {
    dependsOn copyDocker, copyJspToDocker, addLib

    doFirst {
        logger.lifecycle("Building the initial images may take a long time. Have plenty of bandwidth.")
    }

    workingDir 'build/docker-compose'
    commandLine 'docker-compose', 'build'
}

task initContainer(type: Exec) {
    dependsOn jar

    workingDir 'src/test/docker'
    commandLine 'docker', 'compose', 'run', '-e', 'DEMO_RUN_GSH_INIT=true', 'grouper', 'gsh'
}

task runContainer(type: Exec) {
    dependsOn jar, initContainer

    workingDir 'src/test/docker'
    commandLine 'docker', 'compose', 'up', '-d'
}

task stopContainer(type: Exec) {
    workingDir 'src/test/docker'
    commandLine 'docker', 'compose', 'kill'
}

task removeContainer(type: Exec) {
    dependsOn stopContainer

    workingDir 'src/test/docker'
    commandLine 'docker', 'compose', 'rm', '-f'
}

task resetContainer() {
    dependsOn removeContainer
}

clean {
    dependsOn resetContainer
}
